version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: casino_postgres
    environment:
      POSTGRES_DB: casino_db
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casino_user -d casino_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    container_name: casino_migrator
    environment:
      DATABASE_URL: postgres://casino_user:casino_password@postgres:5432/casino_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casino_app
    environment:
      DATABASE_URL: postgres://casino_user:casino_password@postgres:5432/casino_db?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      migrator:
        condition: service_completed_successfully

volumes:
  postgres_data: 